### ISSUE TITLE
the tool doesn't support multiple files in XLIFF

### ISSUE THREAD

**Issue by Gutty1** [zigomir/transync#7]
In cases the input XLIFF file contains string from different files (storyboards, XIB's, etc..)
When running the transync g2x option, the resulting updated XLIFF file get corrupted since takes all the strings like they were in only 1 file instead of ordering by file. Also the xcode header is removed

original XLIFF file created by xcode in german looks like:
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 http://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd">
  <file original="ENTR copy-Info.plist" source-language="en" datatype="plaintext" target-language="de">
    <header>
      <tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="7.3.1" build-num="7D1014"/>
    </header>
    <body>
      <trans-unit id="CFBundleDisplayName">
        <source>${PRODUCT_NAME}</source>
      </trans-unit>
      <trans-unit id="CFBundleName">
        <source>${PRODUCT_NAME}</source>
      </trans-unit>
      <trans-unit id="CFBundleShortVersionString">
        <source>1.5</source>
      </trans-unit>
    </body>
  </file>
  <file original="ENTR dev copy-Info.plist" source-language="en" datatype="plaintext" target-language="de">
    <header>
      <tool tool-id="com.apple.dt.xcode" tool-name="Xcode" tool-version="7.3.1" build-num="7D1014"/>
    </header>
    <body>
      <trans-unit id="CFBundleDisplayName">
        <source>${PRODUCT_NAME}</source>
      </trans-unit>

English file after the transync g2x runned looks like:
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="en" datatype="plaintext" original="file.ext">
        <body>
            <trans-unit id="${PRODUCT_NAME}">
                <source>${PRODUCT_NAME}</source>
                <target>ENTR</target>
            </trans-unit>
            <trans-unit id="1.5">
                <source>1.5</source>
                <target>1.5</target>
            </trans-unit>
            <trans-unit id="Cancel">
                <source>Cancel</source>
                <target>Cancel</target>

**Comment by zigomir** [comment]
I see. I don't use this tool any more for quite some time, so I recommend you to just fork it and customize it to do what you need it to do. 

If you want you can also open a PR and I'll release a new gem version ;)
